import { Bill } from "./schema-and-types";

export const bills: Bill[] = [
  {
    id: "1",
    vendorId: 101,
    vendorName: "ABC Supplies",
    billNumber: "BILL-00001",
    referenceNumber: "INV-2025-001",
    orderNumber: "PO-00045",
    billDate: "2025-08-01",
    dueDate: "2025-08-31",
    paymentTerms: "Net 30",
    subject: "Office Chairs Purchase",
    items: [
      {
        id: "1",
        itemName: "Ergonomic Chair",
        account: "Office Equipment",
        quantity: 10,
        rate: 2500,
        discount: 0,
        tax: "VAT 12%",
        customer: "",
        amount: 28000,
      },
      {
        id: "2",
        itemName: "Delivery Fee",
        account: "Freight Charges",
        quantity: 1,
        rate: 1500,
        discount: 0,
        tax: "VAT 12%",
        customer: "",
        amount: 1680,
      },
    ],
    reportingTags: ["Office", "Q3"],
    subTotal: 29500,
    adjustment: 0,
    total: 29500,
    attachments: ["/uploads/bill-00001.pdf"],
    status: "Open",
  },
  {
    id: "2",
    vendorId: 102,
    vendorName: "XYZ Traders",
    billNumber: "BILL-00002",
    referenceNumber: "INV-2025-002", // added reference number
    orderNumber: "PO-00048",
    billDate: "2025-08-10",
    dueDate: "2025-08-25",
    paymentTerms: "Net 15",
    subject: "Laptop Supplies",
    items: [
      {
        id: "1",
        itemName: "Dell XPS 13",
        account: "IT Equipment",
        quantity: 5,
        rate: 68000,
        discount: 5000,
        tax: "VAT 12%",
        customer: "Project Phoenix",
        amount: 345000,
      },
    ],
    reportingTags: ["IT", "CapEx"],
    subTotal: 340000,
    adjustment: -2000,
    total: 338000,
    attachments: [],
    status: "Draft",
  },
];
