import { PaymentMade } from "./schema-and-types";

export const paymentsMade: PaymentMade[] = [
  {
    id: "PMT-1001",
    vendorId: 1,
    vendorName: "ABC Supplies Co.",
    paymentDate: "2025-08-20",
    paymentMethod: "Bank Transfer",
    referenceNumber: "BT-20250820-001",
    bankCharges: 50,
    tdsDeducted: 100,
    notes: "Partial payment for August bills",
    bills: [
      { billId: "BILL-101", amountPaid: 2000 },
      { billId: "BILL-102", amountPaid: 1500 },
    ],
    totalPaid: 3500,
    amountRefunded: 0,
    excessAmount: 0,
    attachments: ["receipt-1001.pdf"],
  },
  {
    id: "PMT-1002",
    vendorId: 2,
    vendorName: "XYZ Industries",
    paymentDate: "2025-08-19",
    paymentMethod: "Cash",
    referenceNumber: "CASH-08192025",
    bankCharges: 0,
    notes: "Full payment for PO# 5001",
    bills: [{ billId: "BILL-201", amountPaid: 5000 }],
    totalPaid: 5000,
    amountRefunded: 0,
    excessAmount: 0,
    attachments: ["receipt-1002.jpg"],
  },
  {
    id: "PMT-1003",
    vendorId: 1,
    vendorName: "ABC Supplies Co.",
    paymentDate: "2025-08-18",
    paymentMethod: "Check",
    referenceNumber: "CHK-08182025",
    bankCharges: 25,
    notes: "Advance payment for upcoming bills",
    bills: [
      { billId: "BILL-103", amountPaid: 1000 },
      { billId: "BILL-104", amountPaid: 500 },
    ],
    totalPaid: 1500,
    amountRefunded: 0,
    excessAmount: 0,
    attachments: ["check-copy-1003.pdf"],
  },
];
